name: Flow2

on:
  workflow_run:
    workflows:
      - Flow1
    types:
      - completed
    branches:
      - dev
      - master
        
jobs:
  hello2:
    runs-on: ubuntu-latest
    run: echo "HELLO WORLD 2"